### ISSUE TITLE
Atividade 19

### ISSUE THREAD

**Issue by B3nedito** [ProfRonan/contador-de-vogais-B3nedito#2]
"""This program counts the number of vowels in a string.""

def count_vowels (string:str) -> int:

quant = 0

for c in string:

if c in "aeiou" or c in "AEIOU ":

quant+ = 1

return quant

if __name__ == "__main__": count_vowels("")

**Comment by SeuRonao** [comment]
A atividade é para ser feita dando um commit. Eu já disse em sala várias vezes, e inclusive já respondi que assim não podia.
